set serveroutput on;
exec dbms_output.enable(10000000000);

DBMS_OUTPUT.PUT_LINE('Dando de alta los tipos de menu...');
INSERT INTO probasket.TIPOMENU ( CODTIPOMENU, DESCRIPCION) VALUES ('00', 'Tipo Menu Normal');
INSERT INTO probasket.TIPOMENU ( CODTIPOMENU, DESCRIPCION) VALUES ('01', 'Tipo Menu NO Liga');
INSERT INTO probasket.TIPOMENU ( CODTIPOMENU, DESCRIPCION) VALUES ('02', 'Tipo Menu Administrador');
INSERT INTO probasket.TIPOMENU ( CODTIPOMENU, DESCRIPCION) VALUES ('03', 'Tipo Menu Draft');

DBMS_OUTPUT.PUT_LINE('Dando de alta los menus...');
INSERT INTO probasket.MENU ( CODMENU, DESCRIPCION, CODTIPOMENU) VALUES ('001', 'Equipo','00');
INSERT INTO probasket.MENU ( CODMENU, DESCRIPCION, CODTIPOMENU) VALUES ('002', 'Liga', '00');

INSERT INTO probasket.MENU ( CODMENU, DESCRIPCION, CODTIPOMENU) VALUES ('101', 'Crear Liga', '01');
INSERT INTO probasket.MENU ( CODMENU, DESCRIPCION, CODTIPOMENU) VALUES ('102', 'Inscribirse', '01');

INSERT INTO probasket.MENU ( CODMENU, DESCRIPCION, CODTIPOMENU) VALUES ('201', 'Configuracion', '02');
INSERT INTO probasket.MENU ( CODMENU, DESCRIPCION, CODTIPOMENU) VALUES ('202', 'Nacionalidades', '02');
INSERT INTO probasket.MENU ( CODMENU, DESCRIPCION, CODTIPOMENU) VALUES ('203', 'Operaciones', '02');
INSERT INTO probasket.MENU ( CODMENU, DESCRIPCION, CODTIPOMENU) VALUES ('204', 'Roles', '02');
INSERT INTO probasket.MENU ( CODMENU, DESCRIPCION, CODTIPOMENU) VALUES ('205', 'Equipo', '02');
INSERT INTO probasket.MENU ( CODMENU, DESCRIPCION, CODTIPOMENU) VALUES ('206', 'Jugadores', '02');

INSERT INTO probasket.MENU ( CODMENU, DESCRIPCION, CODTIPOMENU) VALUES ('301', 'Draft', '03');
-- .................



INSERT INTO OPERACION ( CODOPERA, DESCRIPCION) VALUES ('0000000001', 'XXXXXXXXXXXXXXXX');
-- .................


--INSERT INTO PROP_CONFIG ( ID, CLAVE, VALOR, COMENTARIO, VISIBLE ) VALUES (1, 'org.quartz.scheduler.instanceName', 'DefaultQuartzScheduler', '#Nombre del planificador', 1); 
