	----------------------------------------
    -- 0º. SOLO HACER PARA BORRAR TODO
    ----------------------------------------
    DBMS_OUTPUT.PUT_LINE('ELMININANDO LA TABLA CONFIGURACION ...');
    DROP TABLE MENU;
    DROP TABLE TIPOMENU;
    DROP TABLE CONFIGURACION;
    DROP TABLE DETECONOMIA;
	DROP TABLE USUARIO;
	DROP TABLE DRAFT;
	DROP TABLE EQUIPOJUGADOR;
	DROP TABLE LIGAJUGADOR;
	DROP TABLE DRAFTTURNO;
	DROP TABLE EQUIPO;
	DROP TABLE LIGA;
	DROP TABLE JUGADOR;
	DROP TABLE OPERACION;
	DROP TABLE ROLE;
	DROP TABLE EQUIPOREAL;
    DROP TABLE ECONOMIA;
	DROP TABLE NACIONALIDAD;
    
	DROP SEQUENCE SEQ_ECONOMIA;
	DROP SEQUENCE SEQ_DETECONOMIA;
	DROP SEQUENCE SEQ_LIGA;
	DROP SEQUENCE SEQ_EQUIPO;
	

    
	----------------------------------------
    -- 1º. CREAR LAS SEQUENCES SI NO EXISTEN
    ----------------------------------------
    CREATE SEQUENCE SEQ_ECONOMIA INCREMENT BY 1 start with 1
	CREATE SEQUENCE SEQ_DETECONOMIA INCREMENT BY 1 start with 1
	CREATE SEQUENCE SEQ_LIGA INCREMENT BY 1 start with 1
	CREATE SEQUENCE SEQ_EQUIPO INCREMENT BY 1 start with 1
	

    
    -------------------------------------    
    -- 2º. CREAR LAS TABLAS SI NO EXISTEN
    -------------------------------------
CREATE TABLE TIPOMENU (
              CODTIPOMENU  	 	VARCHAR(2)  NOT NULL,
              DESCRIPCION       VARCHAR(30)  NOT NULL,
              CONSTRAINT PK_TIPOMENU PRIMARY KEY ( CODTIPOMENU ));	
			  
CREATE TABLE MENU (
              CODMENU  	 		VARCHAR(3)  NOT NULL,
              DESCRIPCION       VARCHAR(50)  NOT NULL,
			  CODTIPOMENU  	 	VARCHAR(2)  NOT NULL,
              CONSTRAINT PK_MENU PRIMARY KEY ( CODMENU ),
			  CONSTRAINT FK_TIPOMENU FOREIGN KEY (CODTIPOMENU) REFERENCES TIPOMENU(CODTIPOMENU));			  
    
CREATE TABLE CONFIGURACION (
              PARAMETRO  	 VARCHAR(50)  NOT NULL,
              VALOR          VARCHAR(50)  NOT NULL,
              CONSTRAINT PK_CONFIGURACION PRIMARY KEY ( PARAMETRO ));

CREATE TABLE NACIONALIDAD (
              CODNACIONALIDAD  	 	VARCHAR(4)  NOT NULL,
              DESCRIPCION           VARCHAR(100)  NOT NULL,
			  RUTAIMAGEN            VARCHAR(150)  NULL,
              CONSTRAINT PK_NACIONALIDAD PRIMARY KEY ( CODNACIONALIDAD ));
			  
CREATE TABLE OPERACION (
              CODOPERA  	 	VARCHAR(3)  NOT NULL,
              DESCRIPCION       VARCHAR(100)  NOT NULL,
              CONSTRAINT PK_OPERACION PRIMARY KEY ( CODOPERA ));

CREATE TABLE ROLE (
              CODROLE  	 		VARCHAR(3)  NOT NULL,
              DESCRIPCION       VARCHAR(100)  NOT NULL,
              CONSTRAINT PK_ROLE PRIMARY KEY ( CODROLE ));
    
CREATE TABLE ECONOMIA (
              CODECONO  	 	VARCHAR(10)  NOT NULL,
              DINERO       		DECIMAL(12,2)   NOT NULL,
              CONSTRAINT PK_ECONOMIA PRIMARY KEY ( CODECONO ));

CREATE TABLE EQUIPOREAL (
              CODEQUIPOREAL	 	VARCHAR(3)  NOT NULL,
              NOMBRE  	 		VARCHAR(50)  NOT NULL,
			  SIGLAS  	 		VARCHAR(5)  NOT NULL,
			  ACTIVO  	 		VARCHAR(1)  NOT NULL,
			  PATROCINIO  	 	VARCHAR(50)  NOT NULL,
              CONSTRAINT PK_EQUIPOREAL PRIMARY KEY ( CODEQUIPOREAL ));
			  
CREATE TABLE DETECONOMIA (
              CODDETECONOMIA 	VARCHAR(12)  NOT NULL,
              FECHA       		DATE  		  NOT NULL,
			  DETALLE  	 		VARCHAR(300) NOT NULL,
			  CODOPERA  	 	VARCHAR(10)  NOT NULL,
			  CODECONO  	 	VARCHAR(10)  NOT NULL,
              CONSTRAINT PK_CODDETECONOMIA PRIMARY KEY ( CODDETECONOMIA ), 
			  CONSTRAINT FK_OPERACION FOREIGN KEY (CODOPERA) REFERENCES OPERACION(CODOPERA),
              CONSTRAINT FK_ECONOMIA FOREIGN KEY (CODECONO) REFERENCES ECONOMIA(CODECONO));
     
 CREATE TABLE LIGA (
		  CODLIGA  	 	VARCHAR(10)  NOT NULL,
		  NOMBRE       	VARCHAR(30)   NOT NULL,
		  PASSWORD 		VARCHAR(200)  NOT NULL,
		  CONSTRAINT PK_LIGA PRIMARY KEY ( CODLIGA ));
		  
 CREATE TABLE EQUIPO (
		  CODEQUIPO	 	VARCHAR(10)  NOT NULL,
		  NOMBRE       	VARCHAR(30)   NOT NULL,
		  POSICION 	 	VARCHAR(4)  NOT NULL,
		  PUNTOTAL 		DECIMAL(12,2)   NOT NULL,
		  CODLIGA  	 	VARCHAR(10)  NOT NULL,
		  CONSTRAINT PK_EQUIPO PRIMARY KEY ( CODEQUIPO ),
		  CONSTRAINT FK_EQ_LIGA FOREIGN KEY (CODLIGA) REFERENCES LIGA(CODLIGA));		  
		  
 CREATE TABLE JUGADOR (
		  CODJUGADOR	 	VARCHAR(10) NOT NULL,
		  ACTIVO  	 		VARCHAR(1)  NOT NULL,
		  NOMBRE       		VARCHAR(20) NOT NULL,
		  APELLIDOS    		VARCHAR(50) NOT NULL,
		  PUESTO  	 		VARCHAR(1)  NOT NULL,
		  ALTURA  	 		VARCHAR(5)  NOT NULL,
		  PESO  	 		VARCHAR(3)  NULL,
		  FECALTA      		DATE 		NOT NULL,
		  PRECIO 			DECIMAL(12,2)   NOT NULL,
		  CODEQUIPOREAL	 	VARCHAR(3)  NOT NULL,
		  CODNACIONALIDAD  	VARCHAR(4)  NOT NULL,
		  CONSTRAINT PK_CODJUGADOR PRIMARY KEY ( CODJUGADOR ),
		  CONSTRAINT FK_JG_EQ_REAL FOREIGN KEY (CODEQUIPOREAL) REFERENCES EQUIPOREAL(CODEQUIPOREAL),
		  CONSTRAINT FK_JG_NACIONALIDAD FOREIGN KEY (CODNACIONALIDAD) REFERENCES NACIONALIDAD(CODNACIONALIDAD));	

CREATE TABLE EQUIPOJUGADOR (
		  CODEQUIPO	 		VARCHAR(10)  NOT NULL,
		  CODJUGADOR	 	VARCHAR(10) NOT NULL,
		  FECALTA      		DATE 		NOT NULL,
		  FECBAJA     		DATE 		NOT NULL,
		  PRECIOVENTA		DECIMAL(12,2)	  NOT NULL,
		  INDEMNIZACION		DECIMAL(12,2)	  NOT NULL,
		  VALORACIONTEMP	DECIMAL(12,2)	  NOT NULL,
		  NOMINA			DECIMAL(12,2)	  NOT NULL,
		  CODROLE	 		VARCHAR(3)  NOT NULL,
		  CONSTRAINT PK_EQUIPOJUGADOR PRIMARY KEY ( CODEQUIPO, CODJUGADOR, FECALTA ),
		  CONSTRAINT FK_EQJ_ROLE FOREIGN KEY (CODROLE) REFERENCES ROLE(CODROLE));	
		  
CREATE TABLE LIGAJUGADOR (
		  CODLIGA  	 		VARCHAR(10)  NOT NULL,
		  CODJUGADOR	 	VARCHAR(10) NOT NULL,
		  FECALTA      		DATE 		NOT NULL,
		  ACTIVO  	 		VARCHAR(1)  NOT NULL,
		  DINERO 			DECIMAL(12,2)	  NOT NULL,
		  CODEQUIPO	 		VARCHAR(10)  NOT NULL,
		  CONSTRAINT PK_LIGAJUGADOR PRIMARY KEY ( CODLIGA, CODJUGADOR, FECALTA ),
		  CONSTRAINT FK_LJ_EQUIPO FOREIGN KEY (CODEQUIPO) REFERENCES EQUIPO(CODEQUIPO));		  

CREATE TABLE USUARIO (
              LOGIN    			VARCHAR(20)  NOT NULL,
			  PASSWORD 			VARCHAR(200)  NOT NULL,
			  EMAIL 			VARCHAR(50)  NOT NULL,
			  NACIMIENTO		VARCHAR(4) NOT NULL,
			  SEXO 				VARCHAR(1)  NOT NULL,
			  ACTIVO			VARCHAR(1)  NOT NULL,
			  ADMINISTRADOR		VARCHAR(1)  NOT NULL,
			  CODECONO  	 	VARCHAR(10)  NOT NULL,
			  CODLIGA   	 	VARCHAR(10)  NOT NULL,
			  CODEQUIPO  	 	VARCHAR(10)  NOT NULL,
			  CONSTRAINT PK_LOGIN PRIMARY KEY ( LOGIN ),
			  CONSTRAINT FK_USR_ECONOMIA FOREIGN KEY (CODECONO) REFERENCES ECONOMIA(CODECONO),
			  CONSTRAINT FK_USR_LIGA FOREIGN KEY (CODLIGA) REFERENCES LIGA(CODLIGA),
			  CONSTRAINT FK_USR_EQUIPO FOREIGN KEY (CODEQUIPO) REFERENCES EQUIPO(CODEQUIPO));
			  

CREATE TABLE DRAFT (
		  CODLIGA  	 		VARCHAR(10)  NOT NULL,
		  CODEQUIPO	 		VARCHAR(10) NOT NULL,
		  CODJUGADOR	 	VARCHAR(10) NOT NULL,
		  ORDEN 			INTEGER   NOT NULL,
		  CONSTRAINT PK_DRAFT PRIMARY KEY ( CODLIGA, CODEQUIPO, CODJUGADOR, ORDEN ),
		  CONSTRAINT FK_DR_LIGA FOREIGN KEY (CODLIGA) REFERENCES LIGA(CODLIGA),
		  CONSTRAINT FK_DR_EQUIPO FOREIGN KEY (CODEQUIPO) REFERENCES EQUIPO(CODEQUIPO),
		  CONSTRAINT FK_DR_JUGADOR FOREIGN KEY (CODJUGADOR) REFERENCES JUGADOR(CODJUGADOR));
		  
CREATE TABLE DRAFTTURNO (
		  CODLIGA  	 		VARCHAR(10)  NOT NULL,
		  CODEQUIPO	 		VARCHAR(10) NOT NULL,
		  TURNO 			INTEGER   NOT NULL,
		  CONSTRAINT PK_DRAFTTURNOS PRIMARY KEY ( CODLIGA, CODEQUIPO, TURNO ),
		  CONSTRAINT FK_DRT_LIGA FOREIGN KEY (CODLIGA) REFERENCES LIGA(CODLIGA),
		  CONSTRAINT FK_DRT_EQUIPO FOREIGN KEY (CODEQUIPO) REFERENCES EQUIPO(CODEQUIPO));	
    
	-------------------------------------
	-- 3º CREAR LOS INDICES SI NO EXISTEN
	-------------------------------------
	
A LA LIGA SE LE DEBERIA HACER UN INDICE CON
		  NOMBRE       	VARCHAR(30)   NOT NULL,
		  PASSWORD 		VARCHAR(200)  NOT NULL,
		  
	--DBMS_OUTPUT.PUT_LINE('CONSULTANDO EXISTENCIA DEL INDICE IDX_QRTZ_J_REQ_RECOVERY ...');		
		
	--SELECT COUNT(1) INTO CONT1 FROM ALL_INDEXES WHERE INDEX_NAME LIKE 'IDX_QRTZ_J_REQ_RECOVERY';
    --IF CONT1 != 1 THEN
--            DBMS_OUTPUT.PUT_LINE('CREAR INDICE IDX_QRTZ_J_REQ_RECOVERY EN LA TABLA QRTZ_JOB_DETAILS');
--			EXECUTE IMMEDIATE  'CREATE INDEX IDX_QRTZ_J_REQ_RECOVERY ON QRTZ_JOB_DETAILS(REQUESTS_RECOVERY)';
--	END IF;    
	
	
	